### ISSUE TITLE
kinetic release

### ISSUE THREAD

**Issue by wjwwood** [orocos/orocos-kdl-release#2]
@smits it looks like it is possible to release this repository into ROS kinetic. Would it be possible to have you do that? I can help if you need it me too.

Thanks!

**Comment by trainman419** [comment]
+1

**Comment by de-vri-es** [comment]
Could we get a bump to 1.3.1 for python-orocos-kdl? 1.3.0 is not compatible with python 3.

**Comment by tfoote** [comment]
Kinetic was released a year ago: https://github.com/ros/rosdistro/pull/10936
Update to 1.3.1 in kinetic: https://github.com/ros/rosdistro/pull/13304
Lunar was just released. https://github.com/ros/rosdistro/pull/14365
